---
output: github_document
---

<!-- NEWS.md is generated from NEWS.Rmd. Please edit that file -->

# News for package "shinybrms"

## shinybrms 1.0.1

### Bug fixes

* `README.md`: Added the requirement of package **devtools**.

## shinybrms 1.0.0 (only GitHub)

First release. Offers support for Bayesian regression models with a Gaussian, Bernoulli or negative binomial distribution for the (univariate) outcome. Currently, only "fixed" (a.k.a. non-varying or population-level) effects are supported for the predictors. "Random" (a.k.a. varying or group-level) effects are not supported yet. Neither supported are most of [**brms**](https://cran.r-project.org/web/packages/brms/index.html)'s other features, like monotonic effects for ordinal predictors or non-linear effects. Interactions are supported, though. For the inspection of the output, only a short summary (from `brms::summary.brmsfit()`) and the possibility to launch [**shinystan**](https://cran.r-project.org/web/packages/shinystan/index.html) is offered.
