app <- ShinyDriver$new("../../")
app$snapshotInit("bacteria-prep", screenshot = FALSE)

app$setInputs(navbar_ID = "Data")
app$setInputs(ex_da_sel = "bacteria")
app$setInputs(navbar_ID = "Likelihood")
app$setInputs(outc_sel = "y")
app$setInputs(dist_sel = "bernoulli")
app$setInputs(likelihood_navlist_ID = "Predictors")
app$setInputs(pred_mainNP_sel = "week")
app$setInputs(pred_mainNP_sel = c("week", "trt"))
app$setInputs(pred_mainPP_sel = "ID")
app$setInputs(pred_int_build = "week")
app$setInputs(pred_int_build = c("week", "trt"))
app$setInputs(pred_int_add = "click")
app$setInputs(navbar_ID = "Prior")
app$setInputs(prior_class_sel = "b")
app$setInputs(prior_text = "student")
app$setInputs(prior_text = "student_")
app$setInputs(prior_text = "student_t")
app$setInputs(prior_text = "student_t(3, 0, 10)")
app$setInputs(prior_add = "click")
app$setInputs(navbar_ID = "Posterior")
app$setInputs(show_advOpts = TRUE)
app$setInputs(advOpts_seed = 6789)
app$setInputs(advOpts_cores = 4)
app$snapshot()
