app <- ShinyDriver$new("../../")
app$snapshotInit("clearFamily", screenshot = FALSE)

app$setInputs(navbar_ID = "Data")
app$setInputs(ex_da_sel = "bacteria")
app$setInputs(navbar_ID = "Likelihood")
app$setInputs(outc_sel = "y")
app$setInputs(dist_sel = "bernoulli")
app$setInputs(navbar_ID = "Prior")
app$snapshot()
app$setInputs(navbar_ID = "Likelihood")
app$setInputs(dist_sel = "")
app$setInputs(navbar_ID = "Prior")
app$snapshot()
