app <- ShinyDriver$new("../../")
app$snapshotInit("clearOutcome", screenshot = FALSE)

app$setInputs(navbar_ID = "Data")
app$setInputs(ex_da_sel = "bacteria")
app$setInputs(navbar_ID = "Likelihood")
app$setInputs(outc_sel = "y")
app$setInputs(dist_sel = "bernoulli")
app$setInputs(navbar_ID = "Prior")
app$snapshot()
app$setInputs(prior_class_sel = "Intercept")
app$setInputs(prior_text = "studen")
app$setInputs(prior_text = "student_")
app$setInputs(prior_text = "student_t")
app$setInputs(prior_text = "student_t(")
app$setInputs(prior_text = "student_t(3")
app$setInputs(prior_text = "student_t(3, ")
app$setInputs(prior_text = "student_t(3, 0, ")
app$setInputs(prior_text = "student_t(3, 0, 3")
app$setInputs(prior_text = "student_t(3, 0, 3)")
app$setInputs(prior_add = "click")
app$snapshot()
app$setInputs(navbar_ID = "Likelihood")
app$setInputs(outc_sel = "")
app$setInputs(navbar_ID = "Prior")
app$snapshot()
