app <- ShinyDriver$new("../../")
app$snapshotInit("interactions", screenshot = FALSE)

app$setInputs(navbar_ID = "Data",
              ex_da_sel = "Arabidopsis")
app$setInputs(navbar_ID = "Likelihood",
              outc_sel = "total.fruits",
              dist_sel = "negbinomial")
app$setInputs(likelihood_navlist_ID = "Predictors")
app$snapshot()
app$setInputs(pred_int_add = "click")
app$snapshot()
app$setInputs(pred_mainNP_sel = c("reg", "rack", "nutrient", "amd", "status"),
              pred_mainPP_sel = c("popu", "gen"))
app$snapshot()
app$setInputs(pred_int_add = "click")
app$snapshot()
app$setInputs(pred_int_build = c("reg", "nutrient"))
app$setInputs(pred_int_add = "click")
app$snapshot()
app$setInputs(pred_int_build = c("nutrient", "reg"))
app$setInputs(pred_int_add = "click")
app$snapshot()
app$setInputs(pred_int_build = c("reg", "nutrient", "popu"))
app$setInputs(pred_int_add = "click")
app$snapshot()
app$setInputs(pred_int_build = c("reg", "nutrient", "amd"))
app$setInputs(pred_int_add = "click")
app$snapshot()
app$setInputs(pred_int_build = c("popu", "gen"))
app$setInputs(pred_int_add = "click")
app$snapshot()
app$setInputs(pred_int_build = c("rack", "amd", "popu", "gen"))
app$setInputs(pred_int_add = "click")
app$snapshot()
app$setInputs(pred_int_build = c("rack", "popu", "gen"))
app$setInputs(pred_int_add = "click")
app$snapshot()
app$setInputs(pred_int_build = c("status", "popu"))
app$setInputs(pred_int_add = "click")
app$snapshot()
