app <- ShinyDriver$new("../../")
app$snapshotInit("interactions", screenshot = FALSE)

app$setInputs(navbar_ID = "Data")
app$setInputs(ex_da_sel = "Arabidopsis")
app$setInputs(navbar_ID = "Likelihood")
app$setInputs(outc_sel = "total.fruits")
app$setInputs(dist_sel = "negbinomial")
app$setInputs(likelihood_navlist_ID = "Predictors")
app$snapshot()
app$setInputs(pred_int_add = "click")
app$snapshot()
app$setInputs(pred_mainNP_sel = "reg")
app$setInputs(pred_mainNP_sel = c("reg", "rack"))
app$setInputs(pred_mainNP_sel = c("reg", "rack", "nutrient"))
app$setInputs(pred_mainNP_sel = c("reg", "rack", "nutrient", "amd"))
app$setInputs(pred_mainNP_sel = c("reg", "rack", "nutrient", "amd", "status"))
app$setInputs(pred_mainPP_sel = "popu")
app$setInputs(pred_mainPP_sel = c("popu", "gen"))
app$snapshot()
app$setInputs(pred_int_add = "click")
app$snapshot()
app$setInputs(pred_int_build = "reg")
app$setInputs(pred_int_build = c("reg", "nutrient"))
app$setInputs(pred_int_add = "click")
app$snapshot()
app$setInputs(pred_int_build = "nutrient")
app$setInputs(pred_int_build = c("nutrient", "reg"))
app$setInputs(pred_int_add = "click")
app$snapshot()
app$setInputs(pred_int_build = "reg")
app$setInputs(pred_int_build = c("reg", "nutrient"))
app$setInputs(pred_int_build = c("reg", "nutrient", "popu"))
app$setInputs(pred_int_add = "click")
app$snapshot()
app$setInputs(pred_int_build = "reg")
app$setInputs(pred_int_build = c("reg", "nutrient"))
app$setInputs(pred_int_build = c("reg", "nutrient", "amd"))
app$setInputs(pred_int_add = "click")
app$snapshot()
app$setInputs(pred_int_build = "popu")
app$setInputs(pred_int_build = c("popu", "gen"))
app$setInputs(pred_int_add = "click")
app$snapshot()
app$setInputs(pred_int_build = "rack")
app$setInputs(pred_int_build = c("rack", "amd"))
app$setInputs(pred_int_build = c("rack", "amd", "popu"))
app$setInputs(pred_int_build = c("rack", "amd", "popu", "gen"))
app$setInputs(pred_int_add = "click")
app$snapshot()
app$setInputs(pred_int_build = "rack")
app$setInputs(pred_int_build = c("rack", "popu"))
app$setInputs(pred_int_build = c("rack", "popu", "gen"))
app$setInputs(pred_int_add = "click")
app$snapshot()
app$setInputs(pred_int_build = "status")
app$setInputs(pred_int_build = c("status", "popu"))
app$setInputs(pred_int_add = "click")
app$snapshot()
