app <- ShinyDriver$new("../../")
app$snapshotInit("priors_switchClass", screenshot = FALSE)

app$setInputs(navbar_ID = "Data")
app$setInputs(ex_da_sel = "bacteria")
app$setInputs(navbar_ID = "Likelihood")
app$setInputs(outc_sel = "y")
app$setInputs(dist_sel = "bernoulli")
app$setInputs(likelihood_navlist_ID = "Predictors")
app$setInputs(pred_mainPP_sel = "ID")
app$setInputs(navbar_ID = "Prior")
app$setInputs(prior_class_sel = "sd")
app$setInputs(prior_coef_sel = "Intercept")
app$setInputs(prior_text = "normal(0, 2.5)")
app$setInputs(prior_add = "click")
app$snapshot()
app$setInputs(prior_coef_sel = "")
app$setInputs(prior_text = "normal(0, 3)")
app$setInputs(prior_add = "click")
app$snapshot()
app$setInputs(prior_class_sel = "Intercept")
app$setInputs(prior_text = "normal(0, 4)")
app$setInputs(prior_add = "click")
app$snapshot()
