app <- ShinyDriver$new("../../")
app$snapshotInit("priors_autoSetEmpty", screenshot = FALSE)

app$setInputs(navbar_ID = "Data")
app$setInputs(ex_da_sel = "bacteria")
app$setInputs(navbar_ID = "Likelihood")
app$setInputs(outc_sel = "y")
app$setInputs(dist_sel = "bernoulli")
app$setInputs(likelihood_navlist_ID = "Predictors")
app$setInputs(pred_mainNP_sel = "week")
app$setInputs(pred_mainPP_sel = "ID")
app$setInputs(pred_int_build = "week")
app$setInputs(pred_int_build = c("week", "ID"))
app$setInputs(pred_int_add = "click")
app$setInputs(navbar_ID = "Prior")
app$setInputs(prior_class_sel = "sd")
app$setInputs(prior_group_sel = "ID")
app$snapshot()
app$setInputs(prior_class_sel = "cor")
app$snapshot()
